name: CI Pipeline

on:
  push:
    branches: [main]
  pull_request:

env:
  ACTIONS_STEP_DEBUG: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Validar sintaxe do script
        run: bash -n status-check.sh

  test:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Simular execução de testes
        run: echo "Running tests" && exit 0

  package:
    runs-on: ubuntu-latest
    needs: [validate, test]
    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Criar arquivo ZIP
        run: zip -r report.zip status-check.sh

      - name: Fazer upload do artefato
        uses: actions/upload-artifact@v3
        with:
          name: relatorio-status
          path: report.zip

  summary:
    runs-on: ubuntu-latest
    needs: package
    steps:
      - name: Gerar resumo do pipeline
        run: |
          echo "## ✅ Resumo do Pipeline" >> $GITHUB_STEP_SUMMARY
          echo "Sistema operacional: ${{ runner.os }}" >> $GITHUB_STEP_SUMMARY
          echo "Branch executada: ${{ github.ref_name }}" >> $GITHUB_STEP_SUMMARY
          echo "::warning::Atenção! Este é um aviso de exemplo."
          echo "::error::Erro simulado para fins de diagnóstico."
          echo "Artefato: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
