name: Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy para Produção
    runs-on: ubuntu-latest
    environment:
      name: production
    steps:
      - name: Simular Deploy
        run: echo "Deploying to ${{ vars.PROD_DOMAIN }}"