name: Monitoramento App

on:
  workflow_dispatch:

jobs:
  usar-env:
    runs-on: ubuntu-latest
    env:
      APP_ENV: ${{ vars.APP_ENV }}
    steps:
      - name: Mostrar variável de ambiente
        run: echo "Ambiente de execução: ${{ env.APP_ENV }}"

  usar-vars:
    runs-on: ubuntu-latest
    steps:
      - name: Acessar SUPPORT_EMAIL via vars
        run: echo "Contato de suporte: ${{ vars.SUPPORT_EMAIL }}"

  usar-secrets:
    runs-on: ubuntu-latest
    steps:
      - name: Acessar API_KEY via secrets
        run: echo "Usando segredo da API (valor oculto)"
        env:
          API_KEY: ${{ secrets.API_KEY }}
